addons:
  - changed-files:
      - any-glob-to-any-file: 'projects/evoplayer/addons/**'

subtitles:
  - changed-files:
      - any-glob-to-any-file: ['**/*sub*/**', '**/*subs*/**']

ui:
  - changed-files:
      - any-glob-to-any-file: 'projects/evoplayer/ui/**'

performance:
  - changed-files:
      - any-glob-to-any-file: ['projects/evoplayer/pp/**', 'tools/bench*']

audio:
  - changed-files:
      - any-glob-to-any-file: ['**/*audio*/**', '**/*surround*/**']

network:
  - changed-files:
      - any-glob-to-any-file: ['projects/evoplayer/addons/src/evo_net.c', 'projects/evoplayer/addons/include/evo_net.h']

playback:
  - changed-files:
      - any-glob-to-any-file: ['projects/evoplayer/media/**', 'projects/evoplayer/main.c']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '*.md']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'scripts/**', 'Makefile', 'projects/**/Makefile']
