/* GENERATED by tools/gen-test-stream.sh - do not edit by hand.
 *
 * An index into test_1080p.h264, which is linked into the payload by
 * test_stream.S. Each entry is one whole access unit, delimited by its
 * NAL-type-9 access unit delimiter, so the probe can hand the decoder
 * exactly one AU without parsing anything at run time.
 */
#ifndef EVO_TEST_STREAM_H
#define EVO_TEST_STREAM_H

#include <stdint.h>

#define TEST_STREAM_WIDTH   1920
#define TEST_STREAM_HEIGHT  1080
#define TEST_STREAM_FPS     30
#define TEST_STREAM_PROFILE 100   /* H.264 High  */
#define TEST_STREAM_LEVEL   40    /* level 4.0   */
#define TEST_STREAM_AU_COUNT 8

typedef struct {
    uint32_t offset;   /* byte offset into test_stream_h264 */
    uint32_t length;   /* whole access unit, start code included */
    uint8_t  isIdr;    /* carries a NAL type 5 slice */
} test_au_t;

/* Annex-B bytes, linked in by test_stream.S. */
extern const uint8_t  test_stream_h264[];
extern const uint32_t test_stream_h264_len;

static const test_au_t kTestAUs[TEST_STREAM_AU_COUNT] = {
    {        0,    50477, 1 },   /* NAL types: 9, 7, 8, 6, 5 */
    {    50477,    36200, 0 },   /* NAL types: 9, 1 */
    {    86677,    36012, 0 },   /* NAL types: 9, 1 */
    {   122689,    35010, 0 },   /* NAL types: 9, 1 */
    {   157699,    34557, 0 },   /* NAL types: 9, 1 */
    {   192256,    34377, 0 },   /* NAL types: 9, 1 */
    {   226633,    33783, 0 },   /* NAL types: 9, 1 */
    {   260416,    30192, 0 },   /* NAL types: 9, 1 */
};

#endif /* EVO_TEST_STREAM_H */
