/*
 * evo_font_glyph — character to glyph, across both font atlases.
 *
 * The UI font (RR_FONT, in assets/renderer_reset_assets.h) has 69 glyphs:
 * letters, digits, and  /._:-+  . Everything else — comma, apostrophe,
 * parenthesis, question mark — was drawn as a 12px gap. Filenames survived
 * that. Prose does not, and the text reader renders nothing but prose, so
 * assets/evo_font_punct.h adds the missing punctuation as a second atlas
 * generated by tools/gen_icons.py.
 *
 * Two atlases means every text routine needs to know which one a character
 * lives in, and there are four of them across two programs — rr_text and
 * rr_text_w in both the player and tools/uiview.c, each with its own copy of
 * the same four-way face switch, plus the player's subtitle measurer. That is
 * the shape of duplication that had already let the icon switches drift, so
 * the lookup lives here once and they all call it.
 *
 * INCLUDE ORDER MATTERS: this header reads RR_* and EVO_PUNCT_* directly, so
 * it must come after both asset headers.
 *
 * Call evo_font_build_tables() once before any text is drawn. It is a plain
 * function rather than a lazy guard because the player draws text from more
 * than one thread and tools/uiview.c does not link pthread — so each program
 * arranges "once" in the way that suits it, and neither pays for a lock in
 * the inner loop.
 */
#ifndef EVO_FONT_H
#define EVO_FONT_H

/* What rr_text has always advanced for a character it cannot draw. Kept so a
 * glyph that is missing from both atlases still moves the pen. */
#define EVO_FONT_MISS_ADV 12

/* The alpha threshold rr_text has always used. Below it a pixel is not ink. */
#define EVO_FONT_INK_MIN 18

typedef struct {
    const unsigned char *atlas;   /* 8-bit coverage, one byte per pixel */
    int atlas_w;                  /* stride of that atlas */
    int sx, sy, sw, sh;           /* the glyph's cell within it */
    int adv;                      /* pen advance */
} evo_font_glyph;

/*
 * index + 1, so 0 means "not in this set" and a zeroed table is a clean set of
 * misses rather than a table of bogus index 0s.
 */
static unsigned char evo_font_rr_map[256];
static unsigned char evo_font_punct_map[256];

static inline void evo_font_build_tables(void)
{
    int i;

    /* Reverse order so an earlier duplicate wins, matching the linear scan
     * this replaced, which returned the first match. */
    for (i = RR_COUNT - 1; i >= 0; i--)
        evo_font_rr_map[(unsigned char)RR_CHARS[i]] = (unsigned char)(i + 1);

    for (i = EVO_PUNCT_COUNT - 1; i >= 0; i--)
        evo_font_punct_map[(unsigned char)EVO_PUNCT_CHARS[i]] =
            (unsigned char)(i + 1);
}

/** Index into RR_CHARS, or -1. Kept for callers that only want the id. */
static inline int evo_font_rr_index(char ch)
{
    return (int)evo_font_rr_map[(unsigned char)ch] - 1;
}

/**
 * Resolve `ch` at `face` (0 SMALL, 1 SUB, 2 MENU, 3 TITLE).
 * Returns 1 and fills *g, or 0 if neither atlas has the character.
 */
static inline int evo_font_find(char ch, int face, evo_font_glyph *g)
{
    int id;

    if (face < 0)
        face = 0;
    if (face > 3)
        face = 3;

    id = (int)evo_font_rr_map[(unsigned char)ch] - 1;
    if (id >= 0) {
        g->atlas = RR_FONT;
        g->atlas_w = RR_FONT_W;
        if (face == 3) {
            g->sx = RR_TITLE_X[id]; g->sy = RR_TITLE_Y[id];
            g->sw = RR_TITLE_W[id]; g->sh = RR_TITLE_H[id];
            g->adv = RR_TITLE_ADV[id];
        } else if (face == 2) {
            g->sx = RR_MENU_X[id]; g->sy = RR_MENU_Y[id];
            g->sw = RR_MENU_W[id]; g->sh = RR_MENU_H[id];
            g->adv = RR_MENU_ADV[id];
        } else if (face == 1) {
            g->sx = RR_SUB_X[id]; g->sy = RR_SUB_Y[id];
            g->sw = RR_SUB_W[id]; g->sh = RR_SUB_H[id];
            g->adv = RR_SUB_ADV[id];
        } else {
            g->sx = RR_SMALL_X[id]; g->sy = RR_SMALL_Y[id];
            g->sw = RR_SMALL_W[id]; g->sh = RR_SMALL_H[id];
            g->adv = RR_SMALL_ADV[id];
        }
        return 1;
    }

    id = (int)evo_font_punct_map[(unsigned char)ch] - 1;
    if (id >= 0) {
        const evo_punct_face *f = &EVO_PUNCT_FACES[face];

        /* The generated cells are the same height as the RR cells for the
         * same face, with the baseline in the same place, so a caller can
         * draw from either without adjusting y. That is the whole point of
         * measuring the atlas rather than guessing at it. */
        g->atlas = f->pix;
        g->atlas_w = f->atlas_w;
        g->sx = f->x[id];
        g->sy = 0;
        g->sw = f->w[id];
        g->sh = f->cell_h;
        g->adv = f->adv[id];
        return 1;
    }

    return 0;
}

/** Advance for one character, including the fallback for unknown ones. */
static inline int evo_font_advance(char ch, int face)
{
    evo_font_glyph g;
    return evo_font_find(ch, face, &g) ? g.adv : EVO_FONT_MISS_ADV;
}

/** Width of a whole string at `face`. */
static inline int evo_font_text_width(const char *t, int face)
{
    int w = 0;
    const char *q;

    if (!t)
        return 0;
    for (q = t; *q; q++)
        w += evo_font_advance(*q, face);
    return w;
}

#endif /* EVO_FONT_H */
