/* Generated by tools/gen_icons.py - do not edit by hand.
 *
 * The punctuation the generated second atlas provides, as a plain
 * string. Pixels live in assets/evo_font_punct.h; this carries the
 * alphabet only, so the UI layer can check what renders without
 * pulling in a megabyte of glyph data.
 */
#pragma once

#define EVO_FONT_PUNCT_CHARS ",'\"!?();[]{}<>=*#|\\~^`%&@$"
