#!/usr/bin/env python3
"""
Embed the RmlUi UI assets (rml/rcss/fonts/icons) into a C++ translation unit.

WHY THIS EXISTS (#60)
    On hardware, directory traversal on the app module's own read-only mount
    (/app0) fails with EPERM - fstatfs/getdents are blocked on that virtual
    mount point - so the RmlUi runtime could never reliably load its .rml/
    .rcss/.ttf/.png files straight out of the .ffpfsc, and commit edc3a08
    worked around it with an out-of-band FTP push to /data/evoplayer/app/
    assets/ on every deploy. That left the package not actually self-
    contained: a bare PPSA99039.ffpfsc copied to another console had no UI.

    Embedding the assets as byte arrays sidesteps the sandbox quirk entirely -
    a plain in-process memory read needs no filesystem call at all, so EPERM
    on directory ops is no longer in the loop. See evo_rmlui_fileinterface.cpp
    (the RmlUi FileInterface that serves these before ever touching disk) and
    evo_rmlui_bundle.cpp (path normalization + lookup).

WHAT IT COVERS
    Everything under projects/evoplayer/assets/{rml,fonts,icons} - the whole
    RmlUi asset set. Currently ~1.3MB uncompressed, embedded as-is (no
    compression - negligible next to the 29MB already baked into the ELF via
    renderer_reset_assets.h).

OUTPUT
    projects/evoplayer/ui_rml/src/evo_rmlui_bundle_data.cpp
        Generated. Defines EVO_RML_BUNDLE[] / EVO_RML_BUNDLE_COUNT declared in
        evo_rmlui_bundle.h. Do not hand-edit - the lookup logic that consumes
        this table lives in evo_rmlui_bundle.cpp instead, which IS hand-
        maintained, so regenerating this file never touches it.

USAGE
    python3 tools/bundle_rml_assets.py
    Re-run after adding/removing/editing anything under assets/rml, fonts or
    icons. package-app.sh and uiview_playback_rml.sh both run this
    automatically before compiling, so a stale commit only bites a manual
    build.

No third-party dependencies - only the standard library.
"""

import os
import re
import sys

ASSET_SUBDIRS = ("rml", "fonts", "icons")
BYTES_PER_LINE = 20


def c_identifier(key):
    """Turn a bundle key like 'rml/launch.rml' into a valid C identifier."""
    return "DATA_" + re.sub(r"[^A-Za-z0-9]", "_", key)


def collect_files(assets_dir):
    """Yields (bundle_key, abs_path) for every file under the covered dirs,
    sorted for a stable, diff-friendly output."""
    entries = []
    for sub in ASSET_SUBDIRS:
        sub_dir = os.path.join(assets_dir, sub)
        if not os.path.isdir(sub_dir):
            continue
        for root, _dirs, files in os.walk(sub_dir):
            for f in sorted(files):
                abs_path = os.path.join(root, f)
                rel = os.path.relpath(abs_path, assets_dir).replace(os.sep, "/")
                entries.append((rel, abs_path))
    entries.sort(key=lambda e: e[0])
    return entries


def emit_array(lines, ident, data):
    lines.append(f"static const unsigned char {ident}[{len(data)}] = {{")
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append(",".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    assets_dir = os.path.join(root, "projects", "evoplayer", "assets")
    out_path = os.path.join(root, "projects", "evoplayer", "ui_rml", "src",
                             "evo_rmlui_bundle_data.cpp")

    entries = collect_files(assets_dir)
    if not entries:
        raise SystemExit(f"no assets found under {assets_dir}/{{{','.join(ASSET_SUBDIRS)}}}")

    lines = [
        "/* Generated by tools/bundle_rml_assets.py - do not edit by hand.",
        " *",
        " * Every file under assets/{rml,fonts,icons}, embedded as a byte array.",
        " * Lookup logic (path normalization, fallback-to-disk decision) lives",
        " * in evo_rmlui_bundle.cpp, which is hand-maintained and stays untouched",
        " * by regenerating this file. See tools/bundle_rml_assets.py and #60.",
        " */",
        '#include "evo_rmlui_bundle.h"',
        "",
    ]

    total_bytes = 0
    idents = []
    for key, abs_path in entries:
        with open(abs_path, "rb") as fh:
            data = fh.read()
        total_bytes += len(data)
        ident = c_identifier(key)
        idents.append((key, ident, len(data)))
        emit_array(lines, ident, data)

    lines.append(f"const EvoRmlBundleFile EVO_RML_BUNDLE[{len(idents)}] = {{")
    for key, ident, size in idents:
        esc = key.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{ "{esc}", {ident}, {size}u }},')
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int EVO_RML_BUNDLE_COUNT = {len(idents)};")
    lines.append("")

    new_content = "\n".join(lines)

    # Skip the write when nothing changed - package-app.sh/uiview_playback_rml.sh
    # run this on every build, and a touched-but-identical generated file would
    # otherwise force a rebuild of evo_rmlui_bundle_data.o (a ~1MB translation
    # unit) plus a dirty-looking git status for no reason.
    if os.path.isfile(out_path):
        with open(out_path, "r", newline="") as f:
            if f.read() == new_content:
                print(f"{out_path} already up to date ({len(idents)} files, {total_bytes} bytes)")
                return

    with open(out_path, "w", newline="\n") as f:
        f.write(new_content)

    print(f"wrote {out_path}  ({len(idents)} files, {total_bytes} bytes)")


if __name__ == "__main__":
    sys.exit(main())
