#!/usr/bin/env bash
# =============================================================================
# tools/gen-test-stream.sh - build the H.264 test bitstream Phase 6 feeds the
# hardware decoder, plus the access-unit index the probe indexes it with.
#
#   ./tools/gen-test-stream.sh                       # regenerate in place
#   ./tools/gen-test-stream.sh --frames 4            # shorter stream
#   ./tools/gen-test-stream.sh --reference           # also dump reference YUV
#
# WHY THE STREAM IS COMMITTED RATHER THAN COPIED TO THE CONSOLE
#   The console's /fs endpoint is read-only, so there is no way to push a file
#   onto the PS5 from the PC without physically moving the USB stick. A probe
#   that needs a hand-copied file is a probe that cannot be re-run from a
#   single command, and this work is already expensive per deploy. The stream
#   is small (a few hundred KB), synthetic, and generated by this script from
#   ffmpeg's own test source, so committing it costs nothing and removes a
#   manual step from every future run. decodeframe_test still accepts an
#   override on /mnt/usb0 for the day a real clip is wanted.
#
# WHY THESE ENCODER SETTINGS
#   -bf 0          no B-frames, so output order == input order. A first decode
#                  test should not have to distinguish "no picture yet" from
#                  "picture reordered".
#   scenecut=0     one IDR at the front and P-frames after it, so the run
#                  exercises reference handling rather than nine independent
#                  IDRs.
#   aud=1          every access unit starts with a NAL of type 9. That is what
#                  makes AU splitting exact rather than heuristic - the decoder
#                  is fed whole access units, and guessing where one ends is
#                  the kind of mistake that gets blamed on the decoder.
#   -profile high -level 4.0
#                  inside what Phase 5 proved the module accepts (profile_idc
#                  100, level_idc 40), on both resource classes.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT}/projects/decodeframe_test"

FRAMES=8
WIDTH=1920
HEIGHT=1080
FPS=30
CRF=20
REFERENCE=0

while (( $# )); do
    case "$1" in
        --frames)    FRAMES="$2"; shift 2 ;;
        --size)      WIDTH="${2%x*}"; HEIGHT="${2#*x}"; shift 2 ;;
        --crf)       CRF="$2"; shift 2 ;;
        --reference) REFERENCE=1; shift ;;
        -h|--help)   sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *)           echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

command -v ffmpeg >/dev/null || {
    echo "ffmpeg is not on PATH - it is what encodes the stream" >&2
    exit 1
}

H264="${OUT_DIR}/test_1080p.h264"
HDR="${OUT_DIR}/test_stream.h"

DURATION="$(python -c "print(f'{${FRAMES}/${FPS}:.6f}')")"

echo "encoding ${FRAMES} frames of ${WIDTH}x${HEIGHT} testsrc2 -> ${H264}"
ffmpeg -hide_banner -loglevel error -y \
    -f lavfi -i "testsrc2=size=${WIDTH}x${HEIGHT}:rate=${FPS}:duration=${DURATION}" \
    -c:v libx264 -profile:v high -level 4.0 -pix_fmt yuv420p \
    -preset medium -crf "${CRF}" \
    -bf 0 -g 250 -x264-params "aud=1:scenecut=0:ref=1" \
    -f h264 "${H264}"

if (( REFERENCE )); then
    REF="${OUT_DIR}/test_1080p_reference.yuv"
    echo "decoding reference planar YUV -> ${REF} (gitignored, for Phase 7)"
    ffmpeg -hide_banner -loglevel error -y -i "${H264}" \
        -pix_fmt yuv420p -f rawvideo "${REF}"
fi

# -----------------------------------------------------------------------------
# Index the access units.
#
# Split on NAL type 9 (access unit delimiter). Every AU therefore begins with
# its own AUD, and AU 0 carries SPS, PPS and the IDR slice - which is what the
# probe feeds first.
# -----------------------------------------------------------------------------
WIDTH="${WIDTH}" HEIGHT="${HEIGHT}" FPS="${FPS}" CRF="${CRF}" \
H264="${H264}" HDR="${HDR}" python - <<'PY'
import os, pathlib

h264 = pathlib.Path(os.environ["H264"])
hdr  = pathlib.Path(os.environ["HDR"])
data = h264.read_bytes()

# Locate every NAL: a start code is 00 00 01, optionally preceded by one more
# 00. Record where the start code begins, so an AU is a contiguous byte range
# that a decoder can be handed verbatim.
starts, i = [], 0
while True:
    j = data.find(b"\x00\x00\x01", i)
    if j < 0:
        break
    starts.append((j - 1 if j > 0 and data[j - 1] == 0 else j, j + 3))
    i = j + 3

nals = []
for k, (sc, payload) in enumerate(starts):
    end = starts[k + 1][0] if k + 1 < len(starts) else len(data)
    nals.append((sc, end, data[payload] & 0x1F))

aus, cur, kinds = [], None, []
for sc, end, t in nals:
    if t == 9 and cur is not None:
        aus.append(cur); kinds.append(cur_kinds)
        cur, cur_kinds = None, []
    if cur is None:
        cur, cur_kinds = [sc, end], []
    else:
        cur[1] = end
    cur_kinds.append(t)
if cur is not None:
    aus.append(cur); kinds.append(cur_kinds)

rows = []
for (s, e), ks in zip(aus, kinds):
    rows.append((s, e - s, 1 if 5 in ks else 0, ks))

hdr.write_text(
    "/* GENERATED by tools/gen-test-stream.sh - do not edit by hand.\n"
    " *\n"
    " * An index into test_1080p.h264, which is linked into the payload by\n"
    " * test_stream.S. Each entry is one whole access unit, delimited by its\n"
    " * NAL-type-9 access unit delimiter, so the probe can hand the decoder\n"
    " * exactly one AU without parsing anything at run time.\n"
    " */\n"
    "#ifndef EVO_TEST_STREAM_H\n"
    "#define EVO_TEST_STREAM_H\n"
    "\n"
    "#include <stdint.h>\n"
    "\n"
    f"#define TEST_STREAM_WIDTH   {os.environ['WIDTH']}\n"
    f"#define TEST_STREAM_HEIGHT  {os.environ['HEIGHT']}\n"
    f"#define TEST_STREAM_FPS     {os.environ['FPS']}\n"
    "#define TEST_STREAM_PROFILE 100   /* H.264 High  */\n"
    "#define TEST_STREAM_LEVEL   40    /* level 4.0   */\n"
    f"#define TEST_STREAM_AU_COUNT {len(rows)}\n"
    "\n"
    "typedef struct {\n"
    "    uint32_t offset;   /* byte offset into test_stream_h264 */\n"
    "    uint32_t length;   /* whole access unit, start code included */\n"
    "    uint8_t  isIdr;    /* carries a NAL type 5 slice */\n"
    "} test_au_t;\n"
    "\n"
    "/* Annex-B bytes, linked in by test_stream.S. */\n"
    "extern const uint8_t  test_stream_h264[];\n"
    "extern const uint32_t test_stream_h264_len;\n"
    "\n"
    "static const test_au_t kTestAUs[TEST_STREAM_AU_COUNT] = {\n"
    + "".join(
        f"    {{ {off:8d}, {ln:8d}, {idr} }},   /* NAL types: "
        f"{', '.join(str(k) for k in ks)} */\n"
        for off, ln, idr, ks in rows)
    + "};\n"
    "\n"
    "#endif /* EVO_TEST_STREAM_H */\n")

print(f"{h264.name}: {len(data)} bytes, {len(rows)} access units")
for n, (off, ln, idr, ks) in enumerate(rows):
    print(f"  AU {n}: offset {off:8d}  length {ln:7d}  "
          f"{'IDR' if idr else 'P  '}  NAL types {ks}")
print(f"wrote {hdr}")
PY
