#!/usr/bin/env python3
"""Derive ui_screen_2d_pq_out.pipe - the UI pipeline for real HDR10 output.

When a HDR10 / HLG video is on screen EVO registers the display as
Bgr10A2Bt2100Pq (media/src/evo_agc_runtime.c, evo_agc_runtime_set_hdr_output),
so everything drawn to the scanout must be a BT.2020 PQ code value. The OSD,
subtitles and toasts are authored in sRGB, so this variant is ui_screen_2d
with one change at the very end of the fragment stage: sRGB -> linear ->
BT.709 to BT.2020 primaries -> scaled to 203 nits for SDR white (ITU-R
BT.2408 "HDR reference white" / graphics white) -> PQ.

It is generated from ui_screen_2d.pipe rather than copied, so a fix to the
UI shader (clipping, feathering) reaches both. Draws into RmlUi's offscreen
layers keep the SDR pipeline; only the scanout gets this one.

    python3 tools/gen_hdr_ui_pipe.py         # then tools/build_agc_pipes.py
"""
from pathlib import Path

SHADER_DIR = Path(__file__).resolve().parents[1] / "projects/evoplayer/shaders/agc"
SRC = SHADER_DIR / "ui_screen_2d.pipe"
DST = SHADER_DIR / "ui_screen_2d_pq_out.pipe"

PQ_HELPERS = """
/* ---- HDR10 output (generated by tools/gen_hdr_ui_pipe.py) ---- */
const float GRAPHICS_WHITE_NITS = 203.0;   /* ITU-R BT.2408 */

float pq_oetf(float nits) {
    float Y = pow(clamp(nits / 10000.0, 0.0, 1.0), 0.1593017578125);
    return pow((0.8359375 + 18.8515625 * Y) / (1.0 + 18.6875 * Y), 78.84375);
}

/* sRGB-authored colour -> BT.2020 PQ code value */
vec3 srgb_to_pq(vec3 c) {
    vec3 lin = pow(clamp(c, 0.0, 1.0), vec3(2.2));
    vec3 bt2020 = vec3(dot(lin, vec3(0.6274, 0.3293, 0.0433)),
                       dot(lin, vec3(0.0691, 0.9195, 0.0114)),
                       dot(lin, vec3(0.0164, 0.0880, 0.8956)));
    vec3 nits = bt2020 * GRAPHICS_WHITE_NITS;
    return vec3(pq_oetf(nits.r), pq_oetf(nits.g), pq_oetf(nits.b));
}

"""

# RmlUi hands premultiplied colour: un-premultiply, convert, re-premultiply,
# so the blend (ONE, ONE_MINUS_SRC_ALPHA) composites PQ over PQ video.
TAIL_OLD = "    out_color = texel;\n}"
TAIL_NEW = """    if (texel.a > 0.0)
        texel.rgb = srgb_to_pq(texel.rgb / texel.a) * texel.a;
    out_color = texel;
}"""


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    if text.count(TAIL_OLD) != 1:
        raise SystemExit(f"{SRC.name}: fragment tail not found - update gen_hdr_ui_pipe.py")
    marker = "void main() {\n    vec4 texel = texture(image, in_uv) * in_color;"
    if text.count(marker) != 1:
        raise SystemExit(f"{SRC.name}: fragment main not found - update gen_hdr_ui_pipe.py")
    text = text.replace(marker, PQ_HELPERS + marker, 1)
    text = text.replace(TAIL_OLD, TAIL_NEW, 1)
    header = ("; ui_screen_2d_pq_out - GENERATED by tools/gen_hdr_ui_pipe.py from\n"
              "; ui_screen_2d.pipe. Edit that file or the generator, not this one.\n")
    DST.write_text(header + text, encoding="utf-8", newline="\n")
    print(f"  wrote {DST.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
