#!/usr/bin/env python3
"""Emit the NID table that the Phase 2 probe resolves on the console.

Phase 1 recovered the real PS5 API names from strings inside the mapped module
images - sceVideodec2*, sceVdecCore*, sceAudiodec*, sceMp4* - and aerolib.csv
supplies each one's NID. This turns that into a C table so the probe can ask
the console, for every candidate module, "do you export this?".

Names come from aerolib by prefix rather than being typed in here, so the
table cannot drift from the catalogue.

    python tools/re/gen_nid_table.py > projects/decoder_test/nid_table.h
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nid import AeroLib, encode          # noqa: E402

# Prefixes worth resolving. Each is a family Phase 1 found evidence for, or a
# family whose ABSENCE is itself a result worth recording.
PREFIXES = [
    "sceAvPlayer",
    "sceVideodec2",
    "sceVideodec",
    "sceVdecCore",
    "sceVideoDecoderArbitration",
    "sceAudiodec",
    "sceMp4",
    "sceSysmodule",
]

# Modules to try loading and probing. The first five are confirmed loadable
# and enumerated (2026-08-10); the rest are hypotheses Phase 1 raised, where a
# failed load is itself a real answer.
#
# ORDER MATTERS AND IS NOT ALPHABETICAL. Loading libSceAudiodec.sprx HUNG the
# payload on 2026-08-10 - the run reached libSceVideodec, logged its exports,
# and never came back. So anything whose answer we actually want goes ahead of
# it, and it goes last, where a hang costs nothing that has not already been
# written to the stick.
MODULES = [
    "libSceAvPlayer.sprx",
    "libSceVdecCore.sprx",
    "libSceVideoDecoderArbitration.sprx",
    "libSceVideodec2.sprx",
    "libSceVideodec.sprx",
    "libSceSysmodule.sprx",
    "libSceMp4.sprx",
    "libSceVdecwrap.sprx",
    "libSceVdecShevc.sprx",
    "libSceVdecSvp9.sprx",
    "libSceFios2.sprx",
    "libSceGnmDriver.sprx",
    "libSceAjm.sprx",
    "libSceAudiodec.sprx",   # suspected hang - keep last
]


def main():
    aero = AeroLib()
    names = []
    for pref in PREFIXES:
        found = sorted(n for n in aero.by_name if n.startswith(pref))
        names.extend((n, aero.by_name[n], pref) for n in found)

    # De-duplicate while keeping the first (most specific) prefix bucket.
    seen = set()
    uniq = []
    for name, nid, pref in names:
        if name in seen:
            continue
        seen.add(name)
        uniq.append((name, nid, pref))

    out = sys.stdout
    out.write("/* GENERATED by tools/re/gen_nid_table.py - do not edit.\n"
              " *\n"
              " * Symbol names recovered in Phase 1 from strings inside the\n"
              " * mapped module images, paired with their NIDs from\n"
              " * aerolib.csv (zecoxao/sce_symbols).\n"
              " *\n"
              " * The NID is precomputed here rather than hashed on the\n"
              " * console so the probe does no work it does not have to, and\n"
              " * so the table is reviewable in the diff.\n"
              " */\n\n")
    out.write("#ifndef EVO_NID_TABLE_H\n#define EVO_NID_TABLE_H\n\n")

    out.write("typedef struct { const char *name; const char *nid; }"
              " evo_nid_t;\n\n")
    out.write("static const evo_nid_t kNidTable[] = {\n")
    for name, nid, pref in uniq:
        assert encode(name) == nid, f"aerolib disagrees with our hash: {name}"
        out.write(f'    {{ "{name}", "{nid}" }},\n')
    out.write("};\n\n")

    out.write("static const char *const kCandidateModules[] = {\n")
    for m in MODULES:
        out.write(f'    "{m}",\n')
    out.write("};\n\n")
    out.write("#endif /* EVO_NID_TABLE_H */\n")

    print(f"/* {len(uniq)} symbols, {len(MODULES)} modules */", file=sys.stderr)


if __name__ == "__main__":
    main()
